# Deploy to GitHub Pages
name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      GOOGLE_TTS_API_KEY: ${{ secrets.GOOGLE_TTS_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Debug Pre-Build
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Original tts-manager.js content:"
          cat tts-manager.js | grep "static API_KEY"
          echo "Environment variable check:"
          echo "API key exists: ${{ secrets.GOOGLE_TTS_API_KEY != '' }}"
          echo "API key length: ${#GOOGLE_TTS_API_KEY}"
          echo "API key first 6 chars: ${GOOGLE_TTS_API_KEY:0:6}"

      - name: Build
        run: node build.js

      - name: Debug Post-Build
        run: |
          echo "Dist directory contents:"
          ls -la dist/
          echo "Built tts-manager.js content:"
          cat dist/tts-manager.js | grep "static API_KEY"
          echo "Verifying key in built file:"
          if grep -q "%%GOOGLE_TTS_API_KEY%%" dist/tts-manager.js; then
            echo "ERROR: Placeholder still exists in built file"
          else
            echo "Placeholder was replaced"
          fi

      - name: Add cache-busting
        run: |
          TIMESTAMP=$(date +%s)
          echo "Adding cache-busting timestamp: $TIMESTAMP"
          sed -i "s|</head>|<meta http-equiv='cache-control' content='no-cache'><meta http-equiv='expires' content='0'><meta http-equiv='pragma' content='no-cache'></head>|g" dist/index.html
          for file in dist/*.js; do
            echo "Processing file: $file"
            mv "$file" "${file%.js}.${TIMESTAMP}.js"
            echo "Renamed to: ${file%.js}.${TIMESTAMP}.js"
            sed -i "s|${file##*/}|${file##*/%.js}.${TIMESTAMP}.js|g" dist/index.html
          done
          echo "Final index.html content:"
          cat dist/index.html | grep ".js"
          echo "Final dist directory contents:"
          ls -la dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true

      - name: Verify Deployment
        run: |
          git checkout gh-pages
          echo "Deployed tts-manager.js content:"
          find . -name "tts-manager*.js" -exec cat {} \; | grep "static API_KEY"
